FROM ubuntu:18.04

RUN apt-get update && \
    apt-get -y install python-pip jq \
    && rm -rf /var/lib/apt/lists/*
RUN pip install -U pip
RUN pip install ansible openstacksdk future shade python-openstackclient python-octaviaclient

WORKDIR /workspace
