apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  influxdb.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "editable": true,
                "name": "myinfluxdatasource",
                "orgId": 1,
                "type": "influxdb",
                "url": "http://influxdb.local:8086",
                "user":"root",
                "password":"root",
                "database":"database",
                "jsonData":{
                  "httpMode": "GET"
                  },
                "version": 1
            }
        ]
    }
